# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
            ],
            options={
                'db_table': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cover_photo', models.ImageField(upload_to=b'')),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('download', models.TextField()),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.DO_NOTHING, to='gaming_patrada.Category')),
            ],
            options={
                'db_table': 'Games',
                'verbose_name_plural': 'Games',
            },
        ),
    ]
