# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'managed': True, 'verbose_name_plural': 'Games'},
        ),
        migrations.RemoveField(
            model_name='games',
            name='slug',
        ),
        migrations.AddField(
            model_name='games',
            name='release',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='cover_photo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='download',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='games',
            name='name',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='requirements',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
