# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0002_auto_20170217_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='Date Released',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
