# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0002_auto_20170307_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='release',
            field=models.DateField(blank=True, null=True),
        ),
    ]
