# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0003_auto_20170307_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='slug',
            field=models.SlugField(default=1),
        ),
    ]
