# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0004_games_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letters', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'letters',
                'managed': True,
            },
        ),
    ]
