# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0004_auto_20170217_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
