# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-18 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0005_auto_20170217_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
