# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0005_letters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letters',
            old_name='letters',
            new_name='letter',
        ),
    ]
