# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0006_auto_20170307_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letters',
            options={'managed': True, 'verbose_name_plural': 'letters'},
        ),
    ]
