# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-18 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0006_auto_20170218_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='games',
            name='slug',
        ),
    ]
