# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0008_auto_20170308_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='release',
            field=models.DateField(blank=True, null=True),
        ),
    ]
