# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-18 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0008_auto_20170218_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(max_length=100)),
                ('GPU', models.CharField(max_length=100)),
                ('RAM', models.CharField(max_length=4)),
                ('memory', models.CharField(max_length=5)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requrements', to='gaming_patrada.Games')),
            ],
        ),
    ]
