# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-18 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0009_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirements',
            name='GPU',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='RAM',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='memory',
        ),
    ]
