# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-18 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0010_auto_20170218_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirements',
            options={'verbose_name_plural': 'Requirements'},
        ),
        migrations.AddField(
            model_name='requirements',
            name='requirements',
            field=models.TextField(default=2, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requirements',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='gaming_patrada.Games'),
        ),
    ]
