# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0010_auto_20170308_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='games',
            name='release',
            field=models.DateField(blank=True, null=True),
        ),
    ]
