# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-18 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0011_auto_20170218_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='downloadlinks',
            field=models.TextField(blank=True),
        ),
    ]
