# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0011_auto_20170311_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='featured',
        ),
        migrations.AddField(
            model_name='games',
            name='rating',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
