# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0012_auto_20170312_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='release',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
