# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0014_remove_games_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='release',
            field=models.DateField(default='1800-5-5'),
        ),
    ]
