# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0017_auto_20170219_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
