# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0018_auto_20170219_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='downloadlinks',
            field=models.URLField(),
        ),
    ]
