# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0020_auto_20170222_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirements',
            name='game',
        ),
        migrations.AddField(
            model_name='games',
            name='requirements',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='games',
            name='download',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.DeleteModel(
            name='Requirements',
        ),
    ]
