# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0021_auto_20170222_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('cover_photo', models.CharField(max_length=100)),
                ('download', models.TextField(max_length=1000)),
                ('requirements', models.TextField(max_length=1000)),
            ],
        ),
    ]
