# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0022_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={},
        ),
        migrations.RemoveField(
            model_name='games',
            name='slug',
        ),
        migrations.AlterField(
            model_name='games',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='games',
            name='cover_photo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='games',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='games',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='games',
            name='requirements',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
