# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0023_auto_20170222_2134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new',
        ),
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name_plural': 'Games'},
        ),
        migrations.AddField(
            model_name='games',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='games',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='gaming_patrada.Category'),
        ),
        migrations.AlterField(
            model_name='games',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to=b'images'),
        ),
        migrations.AlterField(
            model_name='games',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='games',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='games',
            name='requirements',
            field=models.TextField(max_length=1000),
        ),
    ]
