# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0024_auto_20170222_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Games',
        ),
    ]
