# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gaming_patrada', '0025_auto_20170223_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('download', models.TextField(blank=True, null=True)),
                ('cover_photo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Games',
                'managed': False,
            },
        ),
    ]
