# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_patrada', '0027_gams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gams',
            name='category',
        ),
        migrations.DeleteModel(
            name='Gams',
        ),
    ]
